### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by jacekow** [Infineon/DC-Motor-Control#1]
D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp: In constructor 'IfxMcsBiDirectionalMotor::IfxMcsBiDirectionalMotor(IfxMcs::Halfbridge*, IfxMcs::Halfbridge*)':

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:60:13: error: 'FALSE' was not declared in this scope

  mEnabled = FALSE;

             ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp: In member function 'bool IfxMcsBiDirectionalMotor::begin()':

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:76:22: error: 'TRUE' was not declared in this scope

  if(mOut1->active == TRUE || mOut2->active)

                      ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:84:18: error: 'TRUE' was not declared in this scope

  mOut1->active = TRUE;

                  ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:96:9: error: 'FALSE' was not declared in this scope

  return FALSE;

         ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp: In member function 'void IfxMcsBiDirectionalMotor::end()':

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:102:17: error: 'FALSE' was not declared in this scope

  if(mEnabled == FALSE)

                 ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:107:18: error: 'FALSE' was not declared in this scope

  mOut1->active = FALSE;

                  ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp: In member function 'void IfxMcsBiDirectionalMotor::start()':

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:123:13: error: 'TRUE' was not declared in this scope

  mRunning = TRUE;

             ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp: In member function 'void IfxMcsBiDirectionalMotor::stop()':

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:130:13: error: 'FALSE' was not declared in this scope

  mRunning = FALSE;

             ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp: In member function 'void IfxMcsBiDirectionalMotor::update()':

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:212:17: error: 'FALSE' was not declared in this scope

  if(mEnabled == FALSE)

                 ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:218:14: error: 'FALSE' was not declared in this scope

   mRunning = FALSE;

              ^

D:\arduino-1.6.11\libraries\IfxMotorControlShield\src\IfxMcsBiDirectionalMotor.cpp:220:17: error: 'FALSE' was not declared in this scope

  if(mRunning == FALSE)

                 ^

exit status 1

**Comment by mhollfelder** [comment]
TRUE and FALSE seems to be not defined, we need to fix this.
I think that there was the assumption that these keywords are defined for every hardware platform.

For which hardware are you compiling the library?

Best regards,

Manuel

**Comment by jacekow** [comment]
I was compiling the library examples for Arduino Uno but I plan to use this
software (and hardware) on Infineon's Easy Kit with XE164 to drive a
thermoelectric element for temperature stabilization of laser stand.
Best regards,
Jacek Owczarczyk

2017-11-03 12:31 GMT+01:00 Manuel Hollfelder <notifications@github.com>:

**Comment by mhollfelder** [comment]
It is the mentioned issue, I will prepare an update for today and release it asap.
Sorry for the troubles with the Arduino Uno and the compilation.

If you would like to use it for Infineon's Easy Kit with XE164, you would need to modify the code to substitute the Arduino hardware abstraction layer, I assume. 
Should be feasible and sounds interesting :)

Best regards,

Manuel

**Comment by jacekow** [comment]
Thanks, I will keep you informed on the progress


2017-11-07 8:13 GMT+01:00 Manuel Hollfelder <notifications@github.com>:

**Comment by mhollfelder** [comment]
I released a new version 1.0.1 which should fix the TRUE/FALSE problem.
Please test it and if you face issues, let me know.

Best regards,

Manuel

**Comment by jacekow** [comment]
Working smoothly. For initial test I would like to use a bridge consisting
of two Infineon-BTS7960 instead of Infineon-BTN8982. These both halfbriges
seem to be pin compatible and their driving is the same. Or not?

2017-11-07 16:36 GMT+01:00 Manuel Hollfelder <notifications@github.com>:

**Comment by mhollfelder** [comment]
Sorry for the delayed reply. Do you still need further help here?

I am not sure about the question, but I could clarify it internally and come back to you with an answer if still needed.

Best regards,

Manuel

**Comment by jacekow** [comment]
Hi Manuel,
Thank you for asking, it is working now as expected - also with BTS7960
best regards
---------- Forwarded message ----------

**Comment by mhollfelder** [comment]
Great to hear and thank you very much for your reply.
In case you have open questions, please do not hesitate to reopen this issue or open a new one.

Best regards,

Manuel
