### ISSUE TITLE
Unclear currentSense for PWM applications.

### ISSUE THREAD

**Issue by H4ruspex** [Infineon/DC-Motor-Control#2]
Following the application note "NovalithIC™ half-bridge family BTN89xx", the voltage at the IS pin should either be measured phased in the middle of the pwm duty cycle (Section 5.5) or lowpass filtered (Section 4.5.2.3). In this code the first option is not implemented and the shield proposed doesn't include a lowpass filter. The getCurrentSense method gives unreliable results to me.

**Comment by ederjc** [comment]
Thanks for bringing up this issue! Unfortunately, there is no further development planned in this library, as the corresponding product is discontinued. For future DC motor control projects please refer to: https://github.com/Infineon/arduino-motix-btn99x0
