### ISSUE TITLE
Current Sense implementation?

### ISSUE THREAD

**Issue by bondango** [Infineon/DC-Motor-Control#3]
Its unclear is current sense is actually implemented?? is there any example code on how to use this??

**Comment by ederjc** [comment]
Dear @bondango, this product is end of life, please check out our newer DC motor control shields, for example: https://github.com/Infineon/arduino-motix-btn99x0.
There you can also sense current by calling [btn99x0::HalfBridge::get_load_current_in_amps()](https://arduino-motix-btn99x0.readthedocs.io/en/latest/api-ref.html#_CPPv4N7btn99x010HalfBridge24get_load_current_in_ampsEv)
