### ISSUE TITLE
Serial not working

### ISSUE THREAD

**Issue by brato** [Infineon/DC-Motor-Control#4]
On the XMC 1100 debug board the Bidirectional example sketch does not produce any Output. Changing the order of the begin calls of Serial and ifxMcsBiDirectionalMotor it works as expected.

I think the issue is that in the begin call of IfxMcsBiDirectionalMotor.cpp and IfxMcsUniDirectionalMotor.cpp respectively 'pinMode(mOut->pinIs, INPUT);' is called on an analog Pin which is not necessary. As A0 and A1 are defined as 0 and 1  it defines the pins 0 and 1 and thus rx and tx as input.

**Comment by ederjc** [comment]
Thanks for providing a potential fix for this problem! There are no further development plans for this library, as the corresponing product is discontinued. For future DC motor control projects please refer e.g. to: https://github.com/Infineon/arduino-motix-btn99x0
